import { Inter } from 'next/font/google';
import './globals.css';
import Nav from './_components/Nav';
import BottomNav from './_components/BottomNav/BottomNav';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + 'flex flex-col justify-center items-center '}>
        <div className="relative mx-auto max-w-screen-xl  bg-red-30  max-md:my-14">
          <Nav />
          <div className="px-10 mt-24 max-md:px-5">{children}</div>
          <BottomNav />
        </div>
      </body>
    </html>
  );
}
