import { Inter } from 'next/font/google';
import './globals.css';
import Nav from './_components/Nav';
import BottomNav from './_components/BottomNav/BottomNav';
import Footer from './_components/Footer';
import AuthProvider from '@/lib/next-auth';
import RQProvider from './_components/RQProvider';
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'KEYNUT | 커스텀 키보드',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="format-detection" content="telephone=no" />
      </head>
      <body className={inter.className + 'flex flex-col justify-center items-center max-md:mb-bottom-nav-heigth'}>
        <Script
          src="https://t1.kakaocdn.net/kakao_js_sdk/2.7.2/kakao.min.js"
          integrity="sha384-TiCUE00h649CAMonG018J2ujOgDKW/kVWlChEuu4jK2vxfAAD0eZxzCKakxg55G4"
          crossorigin="anonymous"
        ></Script>
        <RQProvider>
          <AuthProvider>
            <Nav />
            <main className="relative main-1280 max-md:pt-0">{children}</main>
            <Footer />
            <BottomNav />
          </AuthProvider>
        </RQProvider>
      </body>
    </html>
  );
}
